name: 'Code owner auto approve'
on:
  pull_request_target:
    types:
      - opened
    branches: [develop]
jobs:
  info:
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.owners.outputs.team }}
      output2: ${{ steps.owners.outputs.members}}
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: npm install
        run: npm i -y octokit @actions/core @actions/github
        
      - name: Parse OWNERS
        id: owners
        run: node index.js
        working-directory: .github/workflows
        env: 
          ORG: ${{ github.event.organization.login }}
          REPO: ${{ github.event.repository.name }}
          PULL: ${{ github.event.pull_request.number }}
          TOKEN: ${{ secrets.TOKEN }}
          
      #debug
      - run: echo ${{ steps.owners.outputs.team }}
      - run: echo ${{ steps.owners.outputs.members}}
      - run: echo ${{ github.actor }}
      - run: echo ${{ secrets.TOKEN_FRONTEND }}
      - run: echo ${{ secrets.TOKEN_BACKEND }}
      - run: echo ${{ secrets.TOKEN_DEVOPS }}
 
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: info
    if: contains(needs.info.outputs.output2, github.actor)
    steps:     
      - uses: hmarr/auto-approve-action@v2.4.0
        if: needs.info.outputs.output1 == 'front'
        with:
          github-token: ${{ secrets.TOKEN_FRONTEND }}
          review-message: "Frontend auto approve"
         
      - uses: hmarr/auto-approve-action@v2.4.0
        if: needs.info.outputs.output1 == 'back'
        with:
          github-token: ${{ secrets.TOKEN_BACKEND }}
          review-message: "Backend auto approve"
         
      - uses: hmarr/auto-approve-action@v2.4.0
        if: needs.info.outputs.output1 == 'devops'
        with:
          github-token: ${{ secrets.TOKEN_DEVOPS }}
          review-message: "Devops auto approve"
