name: Auto tagger
on:
  pull_request:
    branches: ["develop"]
    types:
      - closed

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo BRANCH_NAME=${{github.event.pull_request.head.ref}} >> $GITHUB_ENV
      - run: echo TITLE=${BRANCH_NAME#*/} >> $GITHUB_ENV
      - run: echo "$TITLE"
      - uses: tvdias/github-tagger@v0.0.1
        if: env.TITLE != ''
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{env.TITLE}}"
          commit-sha: "${{env.GITHUB_SHA}}"
